networks:
  aetherlens:
    name: aetherlens_net

services:
  postgres:
    image: postgres:15
    container_name: aetherlens-db
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_PORT=${PG_PORT}
    expose:
      - ${PG_PORT}
    networks:
      - aetherlens

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: aetherlens-api
    depends_on:
      - postgres
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - PG_PORT=${PG_PORT}
      - CHAIN_URL=${CHAIN_URL}
      - API_PORT=${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    entrypoint: ./main
    networks:
      - aetherlens

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: aetherlens-ui
    depends_on:
      - api
    command: "pnpm run start --host 0.0.0.0"
    volumes:
      - ./ui/src:/ui/src
    ports:
      - ${UI_PORT}:${UI_PORT}
    networks:
      - aetherlens